### ISSUE TITLE
Import Error: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by skzidan** [ReZeroE/StarRail#1]
![image](https://user-images.githubusercontent.com/37244053/235336798-3b28576a-da6b-4996-a5e5-625b627c4829.png)

py --version
Python 3.11.3

**Comment by ReZeroE** [comment]
Hi there,

The `starrail` package is a Python module (AKA library) that needs to be `pip` installed in order to work correctly. It does not work the same way as a standalone script (where you called `py honkai_star_rail.py`).

I haven't written any documentation for this module because it's still in the early stages of development. The current features offered by `starrail` are relatively simple and somewhat unstable.

With that being said, here is how you install and run it:

***

**To Install** run:
```shell
pip install starrail
```
OR
```shell
git clone https://github.com/ReZeroE/StarRail.git
cd StarRail
pip install .
```

***

After the installation is complete, run the following **to configure** the module:
```shell
starrail configure
```
then follow the prompted steps to configure the module.

***

Currently, there are only a few basic command-line features implemented (the `starrail` UI is still in development):

1. Starting the game from the command-line:
```shell
starrail start
```
2. Terminating the game from command-line (started with `starrail start`)
```shell
starrail stop
```
3. Show configuration status
```shell
starrail show-config
```
4. Set path to game in module (overwrite previous path)
```shell
starrail set-path
```

**Comment by skzidan** [comment]
![image](https://user-images.githubusercontent.com/37244053/235408231-48eaefb3-a2c5-43a0-8c01-103db49e35c7.png)
same thing also got from starrail configure command . Already did pip install starrail

**Comment by ReZeroE** [comment]
Did you make sure that `starrail` was successfully `pip` installed?

If so, try:
```shell
pip uninstall starrail
pip install starrail==0.0.3
pip show starrail
```
If you could show me the ending output from `pip show starrail` that would help a lot.

**Comment by skzidan** [comment]
![image](https://user-images.githubusercontent.com/37244053/235453940-c862fda8-2384-4c64-8843-2b0336f67a2d.png)
Now it works !! u didnt add automation feature yet am I right?

**Comment by ReZeroE** [comment]
Great! And yes, I'm still in the process of implementing the user interface and the automation features.
