### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by deadetou** [ReZeroE/StarRail#11]
What exactly is this supposed to do?
I installed the pip package and configured it, then did starrail start.
Then nothing happens in game? I'm confused if theres something else I'm supposed to do, or a cli argument that I should use

**Comment by Kurumi1102** [comment]
the UI is still in development so nothing will happen at the moment

**Comment by deadetou** [comment]
So nothing will work at all? Including the cli? It's been a month since release so I hope it'll come out soon lol

**Comment by ReZeroE** [comment]
That's correct, I'm still working on it (unfortunately). I'm the only developer who's working on this and I've been moving lately so I haven't had a lot of time to put into this project.

The auto grinding, award-collection, etc. features are mostly complete in the CLI, but the UI is taking me a while to implement.  I might just release the CLI version first since the UI is really slowing me down.

 I'll be working on this in the upcoming weeks. My game is in urgent need of this module as well.

**Comment by FioX0** [comment]
@ReZeroE Just for FYI, not a massive developer here. But I know my way around with basic python. If you have any sample code of being able to cause "Input" into the game. It would allow me to help you out a bit, with the more "basic" functionality.

I.e Automation of functionality that doesn't require pathing.

As I tried this before and pyautogui simply had not way to actually interact with the game, apparently a known issue with the Lib for some games. However it seems you found a workaround by using elevated permissions.

Regardless I want to follow the structure you set up, which is why I'm waiting for a sample of your implementation of like a calyx or something.

**Comment by ReZeroE** [comment]
@FioX0 Any help is more than welcome! I (most likely) won't be starting on the auto-path feature for a while since the UI needs more work and a robust auto-pathing algorithm is relatively complicated and requires extensive testing.

I'll release the CLI version hopefully sometime soon with the module's structure complete.
